export { default as MagentoBuildIcon } from './MagentoBuildIcon'
export { default as ResponsiveDesignIcon } from './ResponsiveDesignIcon'
export { default as EcommerceConsultancyIcon } from './EcommerceConsultancyIcon'
export { default as PowerfulExtensionsIcon } from './PowerfulExtensionsIcon'
export { default as ExternalIntegrationsIcon } from './ExternalIntegrationsIcon'
export { default as MagentoSupportIcon } from './MagentoSupportIcon'
